Repository open-ephys/bonsai-onix1, pull requests merged in 2024-07, with the labels that each got.

#124 Allow override of CheckLinkState implementation
  OpenEphys.Onix/OpenEphys.Onix/ConfigureFmcLinkController.cs
Labels: feature

#125 Read device ID from type metadata
  OpenEphys.Onix/OpenEphys.Onix/ConfigureAnalogIO.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBno055.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureDS90UB9x.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureDigitalIO.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureFmcLinkController.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHarpSyncInput.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeadstage64ElectricalStimulator.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeartbeat.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureLoadTester.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureMemoryMonitor.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1eBno055.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2e.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eBeta.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eBno055.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureRhd2164.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureTS4231.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureTest0.cs
  OpenEphys.Onix/OpenEphys.Onix/ContextHelper.cs
  OpenEphys.Onix/OpenEphys.Onix/DeviceInfo.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eBno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eBetaData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eBno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eData.cs
Labels: feature, fix

#132 Refactor context task to allow asynchronous dispose
  OpenEphys.Onix/OpenEphys.Onix/ContextTask.cs
  OpenEphys.Onix/OpenEphys.Onix/CreateContext.cs
  OpenEphys.Onix/OpenEphys.Onix/StartAcquisition.cs
Labels: fix

#126 Ensure any BNO polling exceptions are routed
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeartbeat.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureLoadTester.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2e.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eBeta.cs
  OpenEphys.Onix/OpenEphys.Onix/Headstage64ElectricalStimulatorTrigger.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eBno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eBno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/ObservableExtensions.cs
Labels: fix

#151 Remove Rhd2164AmplifierDataFormat
  OpenEphys.Onix/OpenEphys.Onix/ConfigureRhd2164.cs
  OpenEphys.Onix/OpenEphys.Onix/Rhd2164Config.cs
Labels: fix

#147 Refactor common data frame properties into abstract base type
  OpenEphys.Onix/OpenEphys.Onix/AnalogInput.cs
  OpenEphys.Onix/OpenEphys.Onix/AnalogInputDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/Bno055DataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/DataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/DigitalInputDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/HarpSyncInputDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/HeartbeatData.cs
  OpenEphys.Onix/OpenEphys.Onix/HeartbeatDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/ManagedFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/MemoryMonitorData.cs
  OpenEphys.Onix/OpenEphys.Onix/MemoryMonitorDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eBetaDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/Rhd2164DataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231DataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/Test0DataFrame.cs
Labels: feature, fix

#163 Implement missing device properties and enforce argument validation
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeartbeat.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureLoadTester.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureMemoryMonitor.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureTest0.cs
  OpenEphys.Onix/OpenEphys.Onix/DeviceID.cs
  OpenEphys.Onix/OpenEphys.Onix/DeviceManager.cs
  OpenEphys.Onix/OpenEphys.Onix/Headstage64OpticalStimulatorTrigger.cs
  OpenEphys.Onix/OpenEphys.Onix/Test0Data.cs
  OpenEphys.Onix/OpenEphys.Onix/Test0DataFrame.cs
Labels: fix

#164 Rename AnalogIO and DigitalIO to refer to breakout
  OpenEphys.Onix/OpenEphys.Onix/BreakoutAnalogInput.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutAnalogInputDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutAnalogOutput.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutDigitalInput.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutDigitalInputDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutDigitalOutput.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBreakoutAnalogIO.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBreakoutBoard.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBreakoutDigitalIO.cs
Labels: feature, fix

#110 Group frame distribution by device address
  OpenEphys.Onix/OpenEphys.Onix/Bno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutAnalogInput.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutDigitalInput.cs
  OpenEphys.Onix/OpenEphys.Onix/ContextTask.cs
  OpenEphys.Onix/OpenEphys.Onix/HarpSyncInputData.cs
  OpenEphys.Onix/OpenEphys.Onix/HeartbeatData.cs
  OpenEphys.Onix/OpenEphys.Onix/MemoryMonitorData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eBetaData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eData.cs
  OpenEphys.Onix/OpenEphys.Onix/Rhd2164Data.cs
  OpenEphys.Onix/OpenEphys.Onix/StartAcquisition.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1Data.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1GeometricPositionData.cs
Labels: feature

#162 Documentation
  OpenEphys.Onix/OpenEphys.Onix/Bno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/Bno055DataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutAnalogInput.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutAnalogInputDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutAnalogOutput.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutDigitalInput.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutDigitalInputDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutDigitalOutput.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBno055.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBreakoutAnalogIO.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBreakoutBoard.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBreakoutDigitalIO.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeadstage64.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeadstage64ElectricalStimulator.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeadstage64OpticalStimulator.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeartbeat.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureMemoryMonitor.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1eBno055.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1eHeadstage.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2e.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eBeta.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eBetaHeadstage.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eBno055.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eHeadstage.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureRhd2164.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureTS4231V1.cs
  OpenEphys.Onix/OpenEphys.Onix/DataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/DeviceFactory.cs
  OpenEphys.Onix/OpenEphys.Onix/Headstage64ElectricalStimulatorTrigger.cs
  OpenEphys.Onix/OpenEphys.Onix/Headstage64OpticalStimulatorTrigger.cs
  OpenEphys.Onix/OpenEphys.Onix/HeartbeatData.cs
  OpenEphys.Onix/OpenEphys.Onix/HeartbeatDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/MemoryMonitorData.cs
  OpenEphys.Onix/OpenEphys.Onix/MemoryMonitorDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eAdc.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eBno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eRegisterContext.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2QuadShankProbeConfiguration.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eBetaData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eBetaDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eBno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/Rhd2164Config.cs
  OpenEphys.Onix/OpenEphys.Onix/Rhd2164Data.cs
  OpenEphys.Onix/OpenEphys.Onix/Rhd2164DataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1Data.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1DataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1GeometricPositionConverter.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1GeometricPositionData.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1GeometricPositionDataFrame.cs
Labels: documentation

#171 Remove geometric prefix
  OpenEphys.Onix/OpenEphys.Onix/ConfigureTS4231V1.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1Data.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1PositionConverter.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1PositionData.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1PositionDataFrame.cs
Labels: feature, fix

#172 Unify processor architecture and avoid exposing internal implementation classes
  OpenEphys.Onix/OpenEphys.Onix.Design/OpenEphys.Onix.Design.csproj
  OpenEphys.Onix/OpenEphys.Onix.sln
  OpenEphys.Onix/OpenEphys.Onix/ConfigureFmcLinkController.cs
  OpenEphys.Onix/OpenEphys.Onix/DS90UB9x.cs
  OpenEphys.Onix/OpenEphys.Onix/DeviceContext.cs
  OpenEphys.Onix/OpenEphys.Onix/HubConfiguration.cs
  OpenEphys.Onix/OpenEphys.Onix/OpenEphys.Onix.csproj
Labels: fix

#177 Add missing documentation and description strings for all public classes
  OpenEphys.Onix/OpenEphys.Onix/Bno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutAnalogInput.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutAnalogOutput.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutDigitalInput.cs
  OpenEphys.Onix/OpenEphys.Onix/BreakoutDigitalOutput.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBno055.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBreakoutAnalogIO.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBreakoutBoard.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureBreakoutDigitalIO.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHarpSyncInput.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeadstage64.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeadstage64ElectricalStimulator.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeadstage64OpticalStimulator.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureHeartbeat.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureLoadTester.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureMemoryMonitor.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1e.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1eBno055.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV1eHeadstage.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2e.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eBeta.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eBetaHeadstage.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eBno055.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureNeuropixelsV2eHeadstage.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureRhd2164.cs
  OpenEphys.Onix/OpenEphys.Onix/ConfigureTS4231V1.cs
  OpenEphys.Onix/OpenEphys.Onix/ContextTask.cs
  OpenEphys.Onix/OpenEphys.Onix/CreateContext.cs
  OpenEphys.Onix/OpenEphys.Onix/DataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/DeviceFactory.cs
  OpenEphys.Onix/OpenEphys.Onix/HarpSyncInputData.cs
  OpenEphys.Onix/OpenEphys.Onix/HarpSyncInputDataFrame.cs
  OpenEphys.Onix/OpenEphys.Onix/Headstage64ElectricalStimulatorTrigger.cs
  OpenEphys.Onix/OpenEphys.Onix/Headstage64OpticalStimulatorTrigger.cs
  OpenEphys.Onix/OpenEphys.Onix/HeartbeatData.cs
  OpenEphys.Onix/OpenEphys.Onix/HubDeviceFactory.cs
  OpenEphys.Onix/OpenEphys.Onix/MemoryMonitorData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eBno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV1eData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eBetaData.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eBno055Data.cs
  OpenEphys.Onix/OpenEphys.Onix/NeuropixelsV2eData.cs
  OpenEphys.Onix/OpenEphys.Onix/Rhd2164Data.cs
  OpenEphys.Onix/OpenEphys.Onix/StartAcquisition.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1Data.cs
  OpenEphys.Onix/OpenEphys.Onix/TS4231V1PositionData.cs
Labels: documentation
