Repository open-ephys/bonsai-onix1, pull requests merged in 2024-08, with the labels that each got.

#184 Rename hub base class to multi-device factory for clarity
  OpenEphys.Onix/ConfigureBreakoutBoard.cs
  OpenEphys.Onix/ConfigureHarpSyncInput.cs
  OpenEphys.Onix/ConfigureHeadstage64.cs
  OpenEphys.Onix/ConfigureNeuropixelsV1eHeadstage.cs
  OpenEphys.Onix/ConfigureNeuropixelsV2eBetaHeadstage.cs
  OpenEphys.Onix/ConfigureNeuropixelsV2eHeadstage.cs
  OpenEphys.Onix/MultiDeviceFactory.cs
  OpenEphys.Onix/SingleDeviceFactoryConverter.cs
Labels: documentation, feature

#187 Publish packages to github on push to main
  .github/workflows/build.yml
Labels: feature

#189 Minor updates to documentation
  OpenEphys.Onix1/MultiDeviceFactory.cs
  OpenEphys.Onix1/StartAcquisition.cs
Labels: documentation

#196 Publish packages to github on release
  .github/workflows/build.yml
Labels: feature

#197 Update bootstrapper version
  .bonsai/Bonsai.config
Labels: fix

#214 Add configuration GUI for NeuropixelsV2e
  .bonsai/Bonsai.config
  .gitignore
  OpenEphys.Onix1.Design/ChannelConfigurationDialog.Designer.cs
  OpenEphys.Onix1.Design/ChannelConfigurationDialog.cs
  OpenEphys.Onix1.Design/ChannelConfigurationDialog.resx
  OpenEphys.Onix1.Design/ContactTag.cs
  OpenEphys.Onix1.Design/DesignHelper.cs
  OpenEphys.Onix1.Design/GenericDeviceDialog.Designer.cs
  OpenEphys.Onix1.Design/GenericDeviceDialog.cs
  OpenEphys.Onix1.Design/GenericDeviceDialog.resx
  OpenEphys.Onix1.Design/NeuropixelsV2eBno055Dialog.Designer.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eBno055Dialog.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eBno055Editor.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eChannelConfigurationDialog.Designer.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eChannelConfigurationDialog.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eDialog.Designer.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eDialog.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eDialog.resx
  OpenEphys.Onix1.Design/NeuropixelsV2eEditor.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eHeadstageDialog.Designer.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eHeadstageDialog.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eHeadstageDialog.resx
  OpenEphys.Onix1.Design/NeuropixelsV2eHeadstageEditor.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eProbeConfigurationDialog.Designer.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eProbeConfigurationDialog.cs
  OpenEphys.Onix1.Design/NeuropixelsV2eProbeConfigurationDialog.resx
  OpenEphys.Onix1.Design/NeuropixelsV2eProbeConfigurationEditor.cs
  OpenEphys.Onix1.Design/OpenEphys.Onix1.Design.csproj
  OpenEphys.Onix1.Design/Properties/Resources.Designer.cs
  OpenEphys.Onix1.Design/Properties/Resources.resx
  OpenEphys.Onix1.Design/icon.ico
  OpenEphys.Onix1/ConfigureNeuropixelsV2e.cs
  OpenEphys.Onix1/ConfigureNeuropixelsV2eBeta.cs
  OpenEphys.Onix1/ConfigureNeuropixelsV2eBno055.cs
  OpenEphys.Onix1/ConfigureNeuropixelsV2eHeadstage.cs
  OpenEphys.Onix1/Electrode.cs
  OpenEphys.Onix1/NeuropixelsV2.cs
  OpenEphys.Onix1/NeuropixelsV2QuadShankElectrode.cs
  OpenEphys.Onix1/NeuropixelsV2QuadShankProbeConfiguration.cs
  OpenEphys.Onix1/NeuropixelsV2eProbeGroup.cs
  OpenEphys.Onix1/OpenEphys.Onix1.csproj
Labels: feature
